/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacioncomercio.productosGUI;
import aplicacioncomercio.productosBL.productosBL;
import aplicacioncomercio.productosDAL.conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author J P Salmeron Dittamo
 */
public class catalogoForm extends javax.swing.JFrame {
    DefaultTableModel model;
    TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form catalogoForm
     */
    public catalogoForm() {
        initComponents();
        
        String[] titulos = {"Codigo", "Producto", "Marca", "Precio x menor", "Precio x Mayor", "Stock", "Precio de lista"};
        model = new DefaultTableModel(null, titulos);
        tblProductos.setModel(model);
        tblProductos.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        tblProductos.setRowSorter(sorter);
        
        tblProductos.setDefaultRenderer(Object.class, new ColoresStock());
        
        this.mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblProductosIr = new javax.swing.JLabel();
        lblInstruccionesSeleccion = new javax.swing.JLabel();
        lblStockIr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Catálogo:");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProductos.setGridColor(new java.awt.Color(102, 102, 102));
        tblProductos.setShowGrid(true);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Buscar:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("IR A:");

        lblProductosIr.setText("MODIFICAR PRODUCTOS ");
        lblProductosIr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosIrMouseClicked(evt);
            }
        });

        lblInstruccionesSeleccion.setText("Si tiene problemas con la selección, presione aquí!");
        lblInstruccionesSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstruccionesSeleccionMouseClicked(evt);
            }
        });

        lblStockIr.setText("MODIFICAR STOCK");
        lblStockIr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStockIrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInstruccionesSeleccion)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblProductosIr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStockIr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblInstruccionesSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblStockIr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProductosIr, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked

    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        //sorter.setRowFilter(RowFilter.regexFilter(txtBuscar.getText(), 0,1,2,3,4)); //DISTINGUE MAYUS de minu, es más preciso.
        try {

            sorter.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(), 0,1,2,3,4)); //INDISTINTO MAYUS o minus.

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR AL SELECCIONAR");
        }

    }//GEN-LAST:event_txtBuscarKeyReleased

    private void lblProductosIrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosIrMouseClicked
        // TODO add your handling code here:
        productosForm objProdF = new productosForm();
        objProdF.setLocationRelativeTo(null);
        objProdF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblProductosIrMouseClicked

    private void lblInstruccionesSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstruccionesSeleccionMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JOptionPane.showMessageDialog(null, "Error inesperado, estaba cansado cuando hice este mensaje de colapso. Llamame!");
        }
    }//GEN-LAST:event_lblInstruccionesSeleccionMouseClicked

    private void lblStockIrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockIrMouseClicked
        // TODO add your handling code here:
        stockForm objStockForm = new stockForm();
        objStockForm.setLocationRelativeTo(null);
        objStockForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblStockIrMouseClicked
    
    public void mostrarDatos(){
        
        while (model.getRowCount()>0){
            model.removeRow(0);
        
        }
        conexion objConnection = new conexion();
            try {
                
                ResultSet resultado = objConnection.consultarRegistros("SELECT * FROM tablaProductos");
                
                while (resultado.next()){
                    System.out.println(resultado.getString("codigo"));
                    System.out.println(resultado.getString("producto"));
                    System.out.println(resultado.getString("marca"));
                    System.out.println(resultado.getFloat("porMenor"));
                    System.out.println(resultado.getFloat("porMayor"));
                    System.out.println(resultado.getInt("stock"));
                    System.out.println(resultado.getFloat("deLista"));
            
                    Object[] objInfo = {resultado.getString("codigo"),resultado.getString("producto"), resultado.getString("marca"), resultado.getFloat("porMenor"), resultado.getFloat("porMayor"), resultado.getInt("stock"), resultado.getFloat("deLista")};
                    model.addRow(objInfo);
                    
            }
            
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e + " Error al mostrar los datos. Reinicie el programa!");
            }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstruccionesSeleccion;
    private javax.swing.JLabel lblProductosIr;
    private javax.swing.JLabel lblStockIr;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
