/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacioncomercio.productosGUI;

import aplicacioncomercio.productosBL.productosBL;
import aplicacioncomercio.productosDAL.conexion;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author J P Salmeron Dittamo
 */
public class stockForm extends javax.swing.JFrame {

    DefaultTableModel model1;
    TableRowSorter<DefaultTableModel> sorter;
    
    /**
     * Creates new form preciosForm
     */
    public stockForm() {
        initComponents();
        
        String[] titulos = {"codigo", "comprados", "vendidos", "stock", "fecha"};
        model1 = new DefaultTableModel(null, titulos);
        tblStock.setModel(model1);
        tblStock.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model1);
        tblStock.setRowSorter(sorter);

        this.mostrarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCompras = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        txtVentas = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblInstruccionesSeleccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblProductosIr = new javax.swing.JLabel();
        lblCatalogoIr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Stock:");

        jLabel2.setText("Debe ingresar números enteros, haciendo referencia al UNIDADES:");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "codigo", "comprados", "vendidos", "stock", "fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblStock.setShowGrid(true);
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        jLabel3.setText("Código:");

        jLabel4.setText("Comprados:");

        jLabel5.setText("Vendidos:");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel6.setText("Buscar:");

        lblInstruccionesSeleccion.setText("Si tiene problemas con la selección, presione aquí!");
        lblInstruccionesSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstruccionesSeleccionMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("IR A: ");

        lblProductosIr.setText("MODIFICAR PRODUCTOS");
        lblProductosIr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosIrMouseClicked(evt);
            }
        });

        lblCatalogoIr.setText("PÁGINA PRINCIPAL");
        lblCatalogoIr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCatalogoIrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblProductosIr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCatalogoIr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnModificar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCancelar)
                                        .addGap(148, 148, 148)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(lblInstruccionesSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCatalogoIr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProductosIr, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar)
                    .addComponent(lblInstruccionesSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        this.modificarRegistros();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==1){

            try {   
                
                JTable receptor =(JTable)evt.getSource();
            
                txtCodigo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
                txtCompras.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
                txtVentas.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
                                                                                                                    //RECUPERA INFO DE TBL Y COMPLETA TXT
                try{
                    int selection = tblStock.getSelectedRow();   //Hago conversión a coordenadas de la tabla sin filtrar de la columna seleccionada, o sea 
                    if (selection>0) {                           //*(sigue) posición original!!!
                        selection = tblStock.convertRowIndexToModel(selection);
                        txtCodigo.setText(tblStock.getModel().getValueAt(selection,0).toString());
                        txtCompras.setText(tblStock.getModel().getValueAt(selection,1).toString());
                        txtVentas.setText(tblStock.getModel().getValueAt(selection,2).toString());
                    }
                } catch (Exception e) {
                    
                    //txtBuscar.setText("");
                    JOptionPane.showMessageDialog(null, "Error al seleccionar, pruebe de otra manera! :/");
                    JOptionPane.showMessageDialog(null, "1- Escriba el código. 2- Seleccione la fila requerida. 3- Borre lo escrito en el buscador. 4- Haga las modificaciones necesarias en el producto seleccionado. 5- Presione Modificar/Cancelar.");
            }
            
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "***** Error al seleccionar, pruebe de otra manera! *****");
            JOptionPane.showMessageDialog(null, "1- Escriba el código. 2- Seleccione la fila requerida. 3- Borre lo escrito en el buscador. 4- Haga las modificaciones necesarias en el producto seleccionado. 5- Presione Modificar/Cancelar.");
            }
        }
    }//GEN-LAST:event_tblStockMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        try {
            
            sorter.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscar.getText(), 0,1,2,3,4)); //INDISTINTO MAYUS o minus.   
            this.recuperarDatosGUI();
             
               
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL SELECCIONAR");
        }
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.limpiarRegistros();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lblInstruccionesSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstruccionesSeleccionMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JOptionPane.showMessageDialog(null, "1- Escriba el código. 2- Seleccione la fila requerida. 3- Borre lo escrito en el buscador. 4- Haga las modificaciones necesarias en el producto seleccionado. 5- Presione Modificar/Cancelar.");
        }
    }//GEN-LAST:event_lblInstruccionesSeleccionMouseClicked

    private void lblProductosIrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosIrMouseClicked
        // TODO add your handling code here:
        productosForm objProducF = new productosForm();
        objProducF.setLocationRelativeTo(null);
        objProducF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblProductosIrMouseClicked

    private void lblCatalogoIrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatalogoIrMouseClicked
        // TODO add your handling code here:
        catalogoForm objcatalogoF = new catalogoForm();
        objcatalogoF.setLocationRelativeTo(null);
        objcatalogoF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCatalogoIrMouseClicked

    
    public productosBL recuperarDatosGUI(){//Todo lo que el usuario escribe
        
        
        productosBL objProductos= new productosBL();
        
        objProductos.setCodigo(txtCodigo.getText());
        
        int compras = (txtCompras.getText().isEmpty())?0: Integer.parseInt(txtCompras.getText());
        objProductos.setComprados(compras);
        int ventas = (txtVentas.getText().isEmpty())?0: Integer.parseInt(txtVentas.getText());
        objProductos.setVendidos(ventas);
            
        return objProductos;
    
    }
    
    public void mostrarDatos(){
        
        while (model1.getRowCount()>0){
            model1.removeRow(0);
        }
           try {
                conexion objConnection = new conexion();
                ResultSet resultado = objConnection.consultarRegistros("SELECT * FROM tablaStock");
                while (resultado.next()){
                System.out.println(resultado.getString("codigo"));
                
                System.out.println(resultado.getInt("comprados"));
                System.out.println(resultado.getInt("vendidos"));
                System.out.println(resultado.getInt("stock"));
                System.out.println(resultado.getString("fecha"));
            
                Object[] objInfo = {resultado.getString("codigo"), resultado.getInt("comprados"), resultado.getInt("vendidos"),resultado.getInt("stock"), resultado.getString("fecha")};
                model1.addRow(objInfo);

            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Error al mostrar los datos. Reinicie el programa!");
        }
        
        
    }
    
    
    public void eliminarRegistros(){
        conexion objConnection = new conexion();
        
        int fila = tblStock.getSelectedRow();
        //int filas[] = tblProductos.getSelectedRows();
        //for (int i= 0; i< filas.length; i++){
            
        String valor = tblStock.getValueAt(fila, 0).toString(); //columna 0 o sea, código.
            
        try {
            String sentenciaInsert = String.format("DELETE FROM tablaStock WHERE codigo ='"+ valor+"'");
            objConnection.ejecutarSentenciaSQL(sentenciaInsert);
            this.mostrarDatos();
            this.limpiarRegistros();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la fila que desea eliminar.-");
            
        }
    
    }
    
    public void modificarRegistros(){
        
        try {
            conexion objConnection = new conexion();
        
            productosBL objProductos = recuperarDatosGUI();
            
            String timeStamp = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(Calendar.getInstance().getTime());
            
            String sentenciaInsert = String.format("UPDATE tablaStock SET comprados = '%d', vendidos = '%d', stock = '%d', fecha = '"+timeStamp+"' "
                    + "WHERE codigo = '%s'", objProductos.getComprados(), objProductos.getVendidos(), objProductos.getStock(),objProductos.getCodigo());
            
            String sentenciaInsertStockTablaProductos = String.format("UPDATE tablaProductos SET stock = '%d' WHERE codigo = '%s'", objProductos.getStock(), objProductos.getCodigo());
            
            objConnection.ejecutarSentenciaSQL(sentenciaInsert);
            objConnection.ejecutarSentenciaSQL(sentenciaInsertStockTablaProductos);
            this.mostrarDatos();
            this.limpiarRegistros();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo salió mal al actualizar la base de datos. Reinicie el programa.- ");
        }
        
       
    }  
    
    public void limpiarRegistros(){
        
        txtCodigo.setText("");
        txtCompras.setText("");
        txtVentas.setText("");
  
        btnModificar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCatalogoIr;
    private javax.swing.JLabel lblInstruccionesSeleccion;
    private javax.swing.JLabel lblProductosIr;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCompras;
    private javax.swing.JTextField txtVentas;
    // End of variables declaration//GEN-END:variables
}
